name: 'Content Change Validation'
description: 'This action validates if a given directory/file has changed.'
author: 'Paulo Eduardo Peixoto'
branding:
  color: 'blue'
  icon: 'check-square'
inputs:
  directoryOrFile:
    description: 'Directory and/or file that must be evaluated.'
    required: true
  gitHubToken:
    description: 'Personal Access Token.'
    required: true
outputs:
  success:
    description: 'Returns whether or not there was a change in the indicated directory/file.'
runs:
  using: 'node16'
  main: 'dist/index.js'
